# build

FROM node:16-alpine as builder

USER node
WORKDIR /home/node

COPY package*.json ./
RUN npm ci

COPY --chown=node:node . .
RUN VITE_API_URL=http://api.cuddly.gg npm run build && npm prune --production

# app

FROM node:16-alpine as app

ENV NODE_ENV production

USER node
WORKDIR /home/node

RUN npm i serve

COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

CMD ["node_modules/.bin/serve", "-s", "dist", "-l", "80"]